name: continuous build
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: sbt clean coverage test coverageReport
    - name: Coverage Report
      run: sbt coverageReport coveralls
