name: continuous build
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - version: "2.13.3"
    name: build and test project
    steps:
      - name: SBT action
        id: sbt
        uses: lokkju/github-action-sbt@master
        with:
          commands: test