name: continuous build
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - version: "2.13.3"
    name: build and test project
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: sbt build
        uses: lokkju/github-action-sbt@master
        with:
          commands: build
      - name: sbt test
        uses: lokkju/github-action-sbt@master
        with:
          commands: test  
